### ISSUE TITLE
Prototype projection des messages du public

### ISSUE THREAD

**Issue by sabrinakayani** [task-tim/temps#13]

**Comment by CorKarine** [comment]
Grandeur de la typographie tester et fonctionnement sur obs

**Comment by sabrinakayani** [comment]
J'ai créé l'animation des messages textes de conclusion. Ensuite, @CorKarine et moi avions tester la projection durant le cours de Guillaume. Lorsque nous l'avons testé, on a remarqué qu'il y avait plusieurs Fautes d'orthographes. Ensuite, on avait aussi remarqué que la couleur gris pale de fond des message de Sasha ado n'étaient pas visible. (nous l'avons enregistré)

Après ce test, j'ai fait les modifications sur la maquette et l'animation (corriger les erreurs d'orthographes et rendre le gris plus foncé).  Nous avons re-tester la projection durant le cours de Guillaume et le tout était convenable!

**Comment by sabrinakayani** [comment]
@CorKarine et moi avons testé la projection des messages du public durant le cours de Guillaume. Le texte était lisible et il était placé convenable. On l'a filmé et ça était approuvé par toute l'équipe!
