### ISSUE TITLE
Faire prototype de la timeline Max pour les projections et lumières

### ISSUE THREAD

**Issue by angelinajeca** [task-tim/temps#33]

**Comment by Trishng** [comment]
brouillon timeline Max fait sur un tableau blanc à été remis.

**Comment by CorKarine** [comment]
Prototype de lumière et projection sur une timeline de type delay

**Comment by sabrinakayani** [comment]
- [ ] 1.1 - 1 Faire la maquette de l’interface de messagerie.
- [ ] 1.1 - 2 Faire l’animation de l’apparition des messages
- [ ] 1.1 - 3 Installer le projecteur
- [ ] 1.1 - 4 Créer un timeline Max afin que les vidéos se projettent au bon moment automatiquement

**Comment by Trishng** [comment]
Prototype de changement de scène (vidéos) pour projection obs sur une timeline MAX avec @angelinajeca
