### ISSUE TITLE
1.2 Faire le prototype de la timeline Max pour les jeux de lumières

### ISSUE THREAD

**Issue by sabrinakayani** [task-tim/temps#50]
- [x] **1.2 - 1** Installer les lumières sur le plafonds
- [x] **1.2 - 2** Créer des fonctions pour les couleurs de lumières sur le logiciel Q light controller
- [x] **1.2 - 3** Créer des chassers pour les jeux de lumières sur le logiciel Q light controller
- [x] **1.2 - 4** Créer un timeline Max afin que les lumière s’allument au bon moment automatiquement
SUCCÈS

**Comment by sabrinakayani** [comment]
- [ ] 1.2 - 1 Installer les lumières sur le plafonds
- [ ] 1.2 - 2 Créer des fonctions pour les couleurs de lumières sur le logiciel Q light controller
- [ ] 1.2 - 3 Créer des chassers pour les jeux de lumières sur le logiciel Q light controller
- [ ] 1.2 - 4 Créer un timeline Max afin que les lumière s’allument au bon moment automatiquement

**Comment by CorKarine** [comment]
Création de chaser et de fonction dans Q light avec @sabrinakayani 
Prototyper des message midi pour les lumières dans Max avec delay avec @angelinajeca

**Comment by Trishng** [comment]
Création d'un prototype timeline de fonction dans Q light contrôler avec Sput, jit.movie et Max avec @angelinajeca
